### ISSUE TITLE
JF_USER is undefined

### ISSUE THREAD

**Issue by yarinsa** [jfrog/frogbot#150]
**Describe the bug**

I created a setup of yarn2 using the workflow you guys provided. And it's seems like JF_USER is undefined even tho it's set up.

**To Reproduce**
Just do your starter flow

**Expected behavior**
The run will go as planned

**Screenshots**

<img width="938" alt="Screen Shot 2022-09-20 at 15 33 47" src="https://user-images.githubusercontent.com/44482362/191258750-43e07044-6a07-475a-ad4e-a6e3055007c5.png">

**Versions**

- Frogbot version: v2.3.2
- Operating system: Linux (runner)
- JFrog Artifactory version: 
- JFrog Xray version (version 3.29.0 or above is required): 

**Additional context**
I looked in your code I didn't see any place that you are setting up JF_USER in your env. 
I also tried to supply JF_USER in:
1. workflow context
2. job context
3. action context

**Comment by omerzi** [comment]
Hi @yarinsa, thank you for informing us about this issue.
Can you please share the YAML file that you used?

**Comment by yarinsa** [comment]
<details><summary>Frogbot workflow yml</summary>

name: 'Frogbot Scan Pull Request'

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  scan-pull-request:
    runs-on: self-hosted
    # A pull request needs to be approved, before Frogbot scans it. Any GitHub user who is associated with the
    # "frogbot" GitHub environment can approve the pull request to be scanned.
    environment: frogbot
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_USER: ${{ secrets.JF_USER }}
      JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      # Install prerequisites
      - uses: actions/checkout@v3
        with:
          repository: transmit-poc/setup-yarn
          token: ${{ env.GH_TOKEN }}
          path: setup-yarn

      - name: Setup Yarn
        uses: ./setup-yarn
        with:
          artifactory_user: ${{ env.JF_USER }}
          artifactory_password: ${{ env.JF_PASSWORD }}
          node_version: 16.13.1

      # - run: rm .yarnrc.yml
      - uses: actions/checkout@v3
        with:
          repository: transmit-poc/frogbot
          token: ${{ env.GH_TOKEN }}
          path: frogbot
          ref: v2

      - name: Run Frogbot
        uses: ./frogbot
        env:
          # [Mandatory]
          # The command that installs the dependencies
          JF_INSTALL_DEPS_CMD: 'yarn install'

          # [Mandatory]
          # JFrog platform URL (This functionality requires version 3.29.0 or above of Xray)
          JF_URL: ${{ secrets.JF_URL }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JFrog username with 'read' permissions for Xray. Must be provided with JF_PASSWORD
          JF_USER: ${{ secrets.JF_USER }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JFrog password. Must be provided with JF_USER
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

          # [Mandatory]
          # The GitHub token automatically generated for the job
          JF_GIT_TOKEN: ${{ secrets.GH_TOKEN }}

          # Uncomment the below options if you'd like to use them.

          # [Optional, default: https://api.github.com]
          # API endpoint to GitHub
          # JF_GIT_API_ENDPOINT: https://github.example.com

          # [Mandatory if JF_USER and JF_PASSWORD are not provided]
          # JFrog access token with 'read' permissions on Xray service
          # JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # [Optional, default: "."]
          # Relative path to the project in the git repository
          # JF_WORKING_DIR: path/to/package.json/dir

          # [Optional]
          # Xray Watches. Learn more about them here: 
              https://www.jfrog.com/confluence/display/JFROG/Configuring+Xray+Watches
          # JF_WATCHES: <watch-1>,<watch-2>...<watch-n>

          # [Optional]
          # JFrog project. Learn more about it here: https://www.jfrog.com/confluence/display/JFROG/Projects
          # JF_PROJECT: <project-key>

          # [Optional, default: "FALSE"]
          # Displays all existing vulnerabilities, including the ones that were added by the pull request.
          # JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"

</details>

We had to fork the bot to our organization as we are not installing actions that are not verified, so we security review and fork, but its the exact same code as you guys (no change)
 
Setup yarn for me is a custom action trying to deal with the difference of authenticating with jfrog:
For example:
using api_key & user (our local setup)
yarn config set npmAuthIdent user:api_key
using password & user (CI setup)
yarn config set npmAuthIdent (user:password | base64)

<details><summary>Setup yarn</summary>

```
# action.yml
name: "Setup Yarn"
description: "Initial setup for yarn with artifactory credentials"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  artifactory_user:
    description: "Artifactory user name (usually company email)"
    required: true
  artifactory_password:
    description: "Artifactory password (ApiKey can be used for fetching artifacts only)"
    required: true
  node_version:
    description: "Artifactory password"
    required: false
    default: 16.13.1

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: escape undefined variables
      shell: sh
      run: |
        echo "JF_API_KEY=${{ inputs.artifactory_password }}" >> $GITHUB_ENV
        echo "JF_PASSWORD=${{ inputs.artifactory_password }}" >> $GITHUB_ENV
        echo "JF_USER=${{ inputs.artifactory_user }}" >> $GITHUB_ENV
    - name: Setup credentials # Currently tests and compatible with Yarn2+
      shell: sh
      run: |
        corepack enable
        yarn config unset npmAuthIdent
        yarn config set npmAuthIdent $(echo -n '${{ inputs.artifactory_user }}:${{ inputs.artifactory_password }}'| base64)
    - name: Retrieve Yarn Cache
      id: yarn-cache-dir-path
      shell: sh
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      shell: sh
      run: yarn install --immutable
```

</details>

I didn't see any reference of you guys setting this up in the action env [here](https://github.com/jfrog/frogbot/blob/master/action/src/utils.ts#L38)
