### ISSUE TITLE
could not determine the package manager / build tool used by this project for Dotnet Projects

### ISSUE THREAD

**Issue by yalamarthisr** [jfrog/frogbot#241]
We Followed similar pattern for Dotnet Project and Kinda getting below pasted error 
  ```
19:09:20 [Info] Running Frogbot "scan-pull-request" command 
  19:09:21 [Info] Auditing project: /home/runner/work/test/test
  Error: 1 [Error] audit command in /home/runner/work/test/test failed:
  could not determine the package manager / build tool used by this project.
  Error: The process '/opt/hostedtoolcache/frogbot/[RELEASE]/x64/frogbot' failed with exit code 1
```

It would be good to have enough documentation for Dotnet.
My Github action workflows looks like below: 

```
name: "Frogbot Scan Pull Request"
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    # A pull request needs to be approved, before Frogbot scans it. Any GitHub user who is associated with the
    # "frogbot" GitHub environment can approve the pull request to be scanned.
    environment: frogbot
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Install prerequisites
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - uses: jfrog/frogbot@v2
        env:
          JF_URL: 
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_DEPLOYER }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
          JF_REQUIREMENTS_FILE: "test/test.sln"
```

Regards
Sri

**Comment by omerzi** [comment]
Hey @yalamarthisr, Frogbot detects the project's technology by looking for relevant package descriptors. Is there a .sln/.csproj file in the root repository of your project?
BTW, by looking at your yaml file, it seems that you didn't configure your JFrog Platform URL. The JF_REQUIREMENTS_FILE isn't relevant for .NET projects, it's relevant for Pip projects. If you want to use another working directory, please read about the [frogbot-config.yml](https://github.com/jfrog/frogbot/blob/master/docs/frogbot-config.md) file.

**Comment by yalamarthisr** [comment]
@omerzi Thank you for the reply. I removed the Platform URL before pasting it here. I am reading through the following https://github.com/jfrog/frogbot/blob/5bd50f6406e8b07ea83e82a56698486e7c1daf59/docs/templates/.frogbot/frogbot-config.yml#L27-L30 and see we can do dynamic analysis like nuget restore or dotnet restore while doing that how do we pass authentication to our artifactory?. because we typically use **jfrog rt dotnet restore ${{ env.SOLUTION_PATH }}** to restore the projects.

**Comment by omerzi** [comment]
Hey @yalamarthisr, at the moment, we do not support resolving dependencies through Artifactory on Frogbot. However, this feature is currently in development and should be released soon. I'll keep you updated.

**Comment by eyalbe4** [comment]
@yalamarthisr,
Adding to @omerzi message, you do have the option of installing jfrog-cli and running the "jf restore" command insode the GitHub workflow just before running Forgbot. This will work. Since however Frogbot will support restoring the depedencies from Artifactory really soon, you can also wait a bit for Forgbot to support this. This functionality will become available by the end of the month, but most probably sooner. 
We're here to assist you with any follow-up question.

**Comment by yalamarthisr** [comment]
@eyalbe4, in this case I don't think I should use .frogbot/frogbot-config.yml file right?.

**Comment by yalamarthisr** [comment]
@eyalbe4 @omerzi

**Comment by yalamarthisr** [comment]
@eyalbe4 @omerzi I am still getting an error 
```
Error: 2 [Error] audit command in /home/runner/work/test/test failed:
 could not determine the package manager / build tool used by this project.
 Error: The process '/opt/hostedtoolcache/frogbot/[RELEASE]/x64/frogbot' failed with exit code 1
```
```
name: "Frogbot Scan Pull Request"
my workflow looks like below
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        with:
          version: 2.14.0
        env:
          JF_ENV_1: ${{ secrets.ARTIFACTORY_DEPLOYER }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 4.x
      - name: nuget add
        run: |
           nuget sources add -Name Artifactory -source https://xyz.jfrog.io/artifactory/api/nuget/v3/nuget -Username test -Password ${{ secrets.artifactory }}
      - name: nuget restore
        working-directory: ./test
        run: |
          nuget restore ./test -source Artifactory

      - uses: jfrog/frogbot@v2
        env:
          JF_URL: https://xyz.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_DEPLOYER }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
```

My .frogbot/frogbot-config.yaml looks like below:
```
- params:
    git:
      repoName: test
      branches:
        - test
```

**Comment by yalamarthisr** [comment]
@eyalbe4 @eyalbe4 Thank you. I am able to scan my repo. this Is there anyway that we can automate this with out manually approve to scan the repo?.

**Comment by eyalbe4** [comment]
@yalamarthisr,
We're happy to hear that Frogbot works for you now!
By deleting the environment section from your workflow, every new PR will be automatically scanned by Frogbot, without the need for approval.
![image](https://user-images.githubusercontent.com/7830056/219321597-ab23b241-a8f7-48b7-a9ef-d5d933f6cec2.png)

Please note that for security reasons, Frogbot will enforce this approval step by failing the scan, if your GitHub repository is public.
Let us know if you have follow-up questions or suggestions.

**Comment by yalamarthisr** [comment]
@eyalbe4 Thank you!!!

**Comment by eyalbe4** [comment]
Sure @yalamarthisr.
If you'd like Frogbot to scan every pull request without the need to approve the scan by one of the project maintainers, the scanned repository must be private (not have public access). If the project is public, the approval step cannot be removed.

**Comment by yalamarthisr** [comment]
@eyalbe4 Apologies I am asking multiple questions on this. Is there a way we can also see these results or scan lists in our Jfrog artifactory UI under the Xray Tab. 
![Xray](https://user-images.githubusercontent.com/109173179/220451911-8cf9f310-9697-462d-8383-d1f47ad9a6c6.PNG)

**Comment by yalamarthisr** [comment]
Hi @omerzi, @eyalbe4 Is there any way we can see the vulnerabilities reported to under Jfrog Xray in UI.

**Comment by eyalbe4** [comment]
@yalamarthisr,
Sorry for the late response for your last question. We encourage you to ask any question here. We're happy to assist here. Frogbot scans are currently not in the shows in the JFrog Xray UI, but this is something that we're considering adding in the future. Please share with us your needs in terms of the scans visibility.

**Comment by yalamarthisr** [comment]
Hi @eyalbe4, we have a branch specified in .frogbot/frogbot-config.yaml like 
```
- params:
    git:
      repoName: test
      branches:
        - main
```
which means it only scans the vulnerabilities in main?. when a PR is raised to main branch it is scanning only main branch instead the branch where PR is raised. How can we achieve something like this?.
