### ISSUE TITLE
[Urgent] : Use frogbot-config.yml in Project

### ISSUE THREAD

**Issue by AdityaHitachi** [jfrog/frogbot#600]
I want to use the `frogbot-config.yml ` file in my project. I am calling this step in my GitHub Actions pull request workflow, but it's not taking that config file. 

```
- name: FrogBot
  uses: jfrog/frogbot@v2.8.8
  env:
    JF_URL: ***
    JF_ACCESS_TOKEN: ***
    JF_GIT_TOKEN: ***
    JF_FAIL: "FALSE"
```

I have placed the 'frogbot-config.yml' file at the root of my project under the '.frogbot' directory like this `.frogbot/frogbot-config.yml`

**Comment by omerzi** [comment]
Hi @AdityaHitachi, thank you for reporting this issue and using Frogbot.
We have recently fixed a bug related to the frogbot-config.yml. Therefore, I highly recommend upgrading Frogbot to the latest version initially. If the issue persists even after the upgrade, please provide the debug logs generated while running Frogbot for further investigation. To enable the debug logs, kindly add the JFROG_CLI_LOG_LEVEL environment variable and set it to DEBUG.
Awaiting your feedback, please let me know if you require any additional assistance.

**Comment by AdityaHitachi** [comment]
> Hi @AdityaHitachi, thank you for reporting this issue and using Frogbot. We have recently fixed a bug related to the frogbot-config.yml. Therefore, I highly recommend upgrading Frogbot to the latest version initially. If the issue persists even after the upgrade, please provide the debug logs generated while running Frogbot for further investigation. To enable the debug logs, kindly add the JFROG_CLI_LOG_LEVEL environment variable and set it to DEBUG. Awaiting your feedback, please let me know if you require any additional assistance.

Does `frogbot-config.yml` need to be in target branch also ?

**Comment by omerzi** [comment]
@AdityaHitachi, yes, as documented here: https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot/setup-frogbot/frogbot-configuration#where-should-the-frogbot-config.yml-file-be-placed-in-the-repository

**Comment by AdityaHitachi** [comment]
> @AdityaHitachi, yes, as documented here: https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot/setup-frogbot/frogbot-configuration#where-should-the-frogbot-config.yml-file-be-placed-in-the-repository

I am working on a Maven project with multiple subfolders. When creating a pull request to the target branch, I want to scan a specific new submodule each time. I have a file of this type in my source repository.

```
- params:
    git:
      branches:
      - testing-patch1
      repoName: my-test-project
    scan:
      projects:
      - workingDirs:
        - ./submodule1
        - ./submodule2

```
 However, Frogbot is not recognizing or taking this file into account from my source branch.

**Comment by omerzi** [comment]
@AdityaHitachi , could you please attach the debug logs? They would assist us in further investigating the issue.

**Comment by AdityaHitachi** [comment]
> @AdityaHitachi , could you please attach the debug logs? They would assist us in further investigating the issue.

Can you please tell me how the configuration file works with `pull_request target`or `pull_request`? Does the configuration only work with `pull_request_target`?"
Also, for pull_request target, if I have a configuration file in both the target and source branches with different work directories in both files, which file does Frogbot file have to take..

**Comment by AdityaHitachi** [comment]
> @AdityaHitachi , could you please attach the debug logs? They would assist us in further investigating the issue.

I have running workflow as event type `pull_request target` and having config file in source repository. but its not picking up that file. Here is the log

![image](https://github.com/jfrog/frogbot/assets/112469025/76f9ffbd-0d7e-46d4-b1ff-27cf15482789)

**Comment by AdityaHitachi** [comment]
**Even though I specified the version, Frogbot is picking up the latest version. I'm unsure why this is happening.**

![image](https://github.com/jfrog/frogbot/assets/112469025/ecebc5bc-6ef3-4949-8109-081514f61b1b)

**Comment by yahavi** [comment]
@AdityaHitachi 
2.10.0 is the version of the Frogbot GitHub Action. We recommend using `v2`.
To select the Frogbot version you can set the specific version in the "version" argument:
```yaml
- name: FrogBot
  uses: jfrog/frogbot@v2
  env:
    JF_URL: ***
    JF_ACCESS_TOKEN: ***
    JF_GIT_TOKEN: ***
    JF_FAIL: "FALSE"
  with:
    version: 2.19.4
```
