### ISSUE TITLE
The latest version of FrogBot is not detecting DotNet and NuGet

### ISSUE THREAD

**Issue by AdityaHitachi** [jfrog/frogbot#612]
### Describe the bug

While running FrogBot scan with the latest version on a .NET project, FrogBot is not determining the package manager. It shows the error message 'Couldn't determine a package manager or build tool used by this project. Skipping the SCA scan.' However, when I tested it with the older version 2.17.1, it detected the package manager successfully.

### Current behavior

i runned two frogbot scan on  my .net proejet with two differnet version but getting deiffernt result both times
when running frogbot with version 2.17.1 its scan the PR, but with version 2.19.6, it's not scanning

**Case 1**
Here how i am calling this step with version 2.17.1 and getting the  log

```
- name: FrogBot
  if: ${{ env.JF_URL }}    
  uses: jfrog/frogbot@v2
  env:
    JF_URL: ***
    JF_ACCESS_TOKEN: ***
    JF_GIT_TOKEN: ***
    JF_WORKING_DIR: ***
    JF_FAIL: "FALSE"
  with:
    version: 2.17.1 
```
_Log Screenshot_ : -

![image](https://github.com/jfrog/frogbot/assets/112469025/a1c7bbec-97c5-4e77-8ff3-7217ec00d2f0)

Case 2
Here how i am calling this step with version 2.19.6 and getting the log

```
- name: FrogBot
  if: ${{ env.JF_URL }}    
  uses: jfrog/frogbot@v2
  env:
    JF_URL: ***
    JF_ACCESS_TOKEN: ***
    JF_GIT_TOKEN: ***
    JF_WORKING_DIR: ***
    JF_FAIL: "FALSE"
  with:
    version: 2.19.6 
```
_Log Screenshot_ : -

![image](https://github.com/jfrog/frogbot/assets/112469025/50120a42-619b-4e2d-a9b5-360a72f387ab)

### JFrog Frogbot version

2.19.6

### Package manager info

.NET CLI and NuGet

### Git provider

GitHub

### Operating system type and version

linux
