### ISSUE TITLE
Avoid creating PRs

### ISSUE THREAD

**Issue by Jetski5822** [jfrog/frogbot#634]
**Is your feature request related to a problem? Please describe.**
Currently FrogBot will always create PRs - https://github.com/jfrog/frogbot/blob/aecbbb6b4a463f515676163369347a3f4b20aaf7/scanrepository/scanrepository.go#L153 

This is not always desirable - we only want it to tell us, hey - you have an issue. I dont want it to try to fix it for me - yet.

**Describe the solution you'd like to see**

Provide an option to opt out of PR creation.

**Comment by attiasas** [comment]
Hi @Jetski5822,

Thank you for submitting this feature request. We will prioritize it, and implementation is planned for future versions. We will keep you updated on the progress.

**Comment by florestan-bardeau-sg** [comment]
Hello,

I'm getting the same problem even with the proper env config or maybe I missed some thing.

Logt std out:

```txt
 Error: 1 [Error] the following errors occured while fixing vulnerabilities in '/home/runner/_work/_temp/jfrog.cli.temp.-1*******
  failed while creating a fixing pull request for: com***** with error: 
  git push failed with error: authorization failed
  failed while creating a fixing pull request for: com.google.p****with error: 
  git push failed with error: authorization failed
  Error: The process '/home/runner/_work/_tool/frogbot/[RELEASE]/x64/frogbot' failed with exit code 1
```


And my config is:

```yml
- name: JFrog Frogbot Security Scan [DIFFERENTIAL - New Issues Only]
        uses: ***/frogbot@v2
        with:
          version: latest
        env:
          JF_URL: ${{ ****  }}
          JF_ACCESS_TOKEN: ${{ **** }}
          JF_GIT_TOKEN: ${{ **** }}
          JF_GIT_API_ENDPOINT: ${{ github.api_url }}

          JF_RELEASES_REPO: "jfrog-releases"

          JF_ALLOW_PARTIAL_RESULTS: "TRUE"
          JF_INCLUDE_ALL_VULNERABILITIES: "FALSE"
          JF_FAIL: "FALSE"
          JF_USE_WRAPPER: "FALSE"
          JF_SKIP_AUTOFIX: "TRUE"
          JF_FIX: "FALSE"
          JF_FIXABLE_ONLY: "FALSE"
          JF_AVOID_EXTRA_MESSAGES: "TRUE"

```

I didn't want to give the write access because I would like to have only the issue recap. I thought with   JF_SKIP_AUTOFIX: "TRUE" it will work.

To give more information I using frogbot from a company env.

Thank for your time :)
