### ISSUE TITLE
Support for yarn3 workspaces?

### ISSUE THREAD

**Issue by Feinminen** [jfrog/frogbot#674]
I'm encountering an issue while setting up frogbot in my project that utilizes yarn 3.6.1 with workspaces. It seems that the installation command provided in the frogbot configuration is not executing correctly.

### Context:

Monorepo Structure:
<img width="263" alt="image" src="https://github.com/jfrog/frogbot/assets/44312820/134dfeca-4d5d-4030-a2e8-4374a512981e">

frogbot-config.yml content:

```
- params:
    scan:
      projects:
        - installCommand: yarn // also tried: yarn install
          workingDirs:
            - packages/lib
```

### Issue:

I'm encountering the following error:
![image](https://github.com/jfrog/frogbot/assets/44312820/2eea6edf-409f-43dc-ad6d-c9d09ff14f21)

It seems that frogbot is attempting to install dependencies with 'npm' despite specifying 'yarn' as the installation command in the configuration file.

### Question:

Could it be that frogbot lacks support for yarn3 workspaces, or am I potentially setting up frogbot incorrectly?

I appreciate any insights or assistance you can provide on this matter. Thank you in advance for your help!
