### ISSUE TITLE
Multiple technologies in one repository

### ISSUE THREAD

**Issue by fellinga** [jfrog/frogbot#774]
I could not find docs on how to use FrogBot with multiple technologies in the same repository. I am working on a project that is based on dotnet but also has a node frontend in a subfolder. I suppose I could run the script in the root folder with JF_INSTALL_DEPS_CMD="dotnet restore" and in /frontend with JF_INSTALL_DEPS_CMD='yarn install' but I think I have read that FrogBot would delete the previous pull request comment.

Can you suggest any best practices?

**Comment by attiasas** [comment]
Hi @fellinga, Sorry for the delay.
You can try to configure 2 projects using our [frogbot-configuration](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot/setup-frogbot/frogbot-configuration)
```
- params:
    git:
      repoName: repo-name
      branches:
        - master
    scan:
      projects:
        - workingDirs:
            - "."
          installCommand: "dotnet restore"
        - workingDirs:
            - "./frontend-dir"
          installCommand: "yarn install"
```

also you can avoid deleting previous comment using `JF_AVOID_PREVIOUS_PR_COMMENTS_DELETION=true`
