### ISSUE TITLE
FrogBot not showing as a tool in Security -> Code Scanning

### ISSUE THREAD

**Issue by nbaju1** [jfrog/frogbot#777]
### Describe the bug

The "Frogbot Scan Pull Request" code scanning tool does not show up in the UI after being added.

### Current behavior

The action is scanning as expected without failures. Python project is being installed with poetry and scanned.

Snip from the PR which deployed the tool:
![Image](https://github.com/user-attachments/assets/df2cbf7f-fa47-47b3-9b5b-5d5e648d1d7e)

### Reproduction steps

Workflow being used.

```
name: "Frogbot Scan Pull Request"
on:
  pull_request:
    branches:
      - master
permissions:
  pull-requests: write
  contents: read
  id-token: write
  security-events: write
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry
        run: pip install poetry

      - uses: jfrog/frogbot@5d9c42c30f1169d8be4ba5510b40e75ffcbbc2a9 # v2.21.2
        env:
          JF_URL: "https://redacted.jfrog.io/"
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_DEPS_REPO: "pypi-virtual"
        with:
          oidc-provider-name: github-provider
          oidc-audience: github-audience
```

### Expected behavior

The tool to show up in the Security -> Code Scanning tab.

### JFrog Frogbot version

2.23.1

### Package manager info

poetry 1.8.4, pyproject.toml

### Git provider

GitHub

### Operating system type and version

Ubuntu 22.04.5

### JFrog Xray version

3.106.5

**Comment by tamer-abdulghani** [comment]
I'm having the same issue, we have added the necessary workflows to enable jfrogbot (repository scan, pull request, scan and fix). 

![Image](https://github.com/user-attachments/assets/52c94e48-b38c-4f65-a511-b82366a85e03)

for some reason, those alerts are not being shown in the code scanning alerts in security tab in GitHub Enterprise.

![Image](https://github.com/user-attachments/assets/fb235db1-f21b-44f1-a37b-fd1d3aae83db)

any idea why this is happening or how to resolve it ?

we used below templates as pipeline: 

```
name: "Scan Repository"
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  security-events: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main"]
    steps:
      - uses: jfrog/frogbot@v2.25.0
        env:
          JF_URL: https://example.jfrog.io
          JF_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.CI_PAT }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_FAIL: "FALSE"
          JF_FIXABLE_ONLY: "TRUE"
          JF_ALLOWED_LICENSES: "MIT, Apache-2.0"
          JF_AVOID_EXTRA_MESSAGES: "TRUE"

```

```
name: "Scan Pull Request"
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - uses: jfrog/frogbot@v2.25.0
        env:
          JF_URL: https://example.jfrog.io
          JF_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.CI_PAT }}
          JF_FAIL: "FALSE"
          JF_FIXABLE_ONLY: "TRUE"
          JF_MIN_SEVERITY: "High"
          JF_ALLOWED_LICENSES: "MIT, Apache-2.0"
          JF_AVOID_EXTRA_MESSAGES: "TRUE"
```
