### ISSUE TITLE
Syntax error in template from "Setup Frogbot Using Azure Pipelines"

### ISSUE THREAD

**Issue by mikeKuester** [jfrog/frogbot#794]
### Describe the bug

The template "Scanning repository branches and fixing issues" in the documentation [Setup Frogbot Using Azure Pipelines](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot/setup-frogbot/setup-frogbot-using-azure-pipelines) doesn't work, if someone wants to use user / password instead of the access token.

```yaml
         env:
            # [Mandatory]
            # JFrog platform URL (This functionality requires version 3.29.0 or above of Xray)
            JF_URL: $(JF_URL)

            # [Mandatory if JF_USER and JF_PASSWORD are not provided]
            # JFrog access token with 'read' permissions for Xray
            JF_ACCESS_TOKEN: $(JF_ACCESS_TOKEN)

            # [Mandatory if JF_ACCESS_TOKEN is not provided]
            # JFrog user and password with 'read' permissions for Xray
            # JF_USER: $JF_USER
            # JF_PASSWORD: $JF_PASSWORD

            # [Mandatory]
            # Azure Repos personal access token with Code -> Read & Write permissions
            JF_GIT_TOKEN: $(JF_GIT_TOKEN)
            ...
```

The normal behavoir would be to add the # before the line with the JF_ACCESS_TOKEN and remove it for JF_USER and JF_PASSWORD, but this won't work ...

I got always an 401 error "Bad Credentials":

```text
08:02:06 [Info] Running Frogbot "scan-repository" command
08:02:07 [Error] got unexpected server response while attempting to get JFrog Xray entitlements response for contextual_analysis:
server response: 401 Unauthorized
{
  "error": "Bad Credentials"
}
```

The problem is, that the brackets are missing in the commented lines. Please fix that in the docs.

```yaml

            # --- This is the snippet from the template:
            # JF_USER: $JF_USER
            # JF_PASSWORD: $JF_PASSWORD

            # --- If a user only uncomments this lines, the usage of the variables has a syntax error!
            JF_USER: $JF_USER
            JF_PASSWORD: $JF_PASSWORD

            # --- You have to add the brackets: $(...)
            JF_USER: $(JF_USER)
            JF_PASSWORD: $(JF_PASSWORD)

```

### Current behavior

Pipeline ends with error.

### JFrog Frogbot version

-

### Package manager info

-

### Git provider

Azure DevOps

### Operating system type and version

-
